export const ACTIVE_STATUSES = [
  'APPROVED',
  'PENDING_MODERATION',
  'PENDING_APPROVAL',
];

export const COMPLETED_STATUSES = [
  'SOLD',
  'DECLINED',
  'BLOCKED',
  'EXPIRED',
  'DRAFT',
  'DISCONTINUED',
];

export const ALL_STATUSES = [...ACTIVE_STATUSES, ...COMPLETED_STATUSES];

export const PUBLISHABLE_STATUSES = ['DRAFT', 'EXPIRED', 'SOLD', 'DISCONTINUED'];
